### ISSUE TITLE
Failure to converge and panic under `initialize_plusplus`

### ISSUE THREAD

**Issue by OmnipotentEntity** [genbattle/rkm#1]
I'm currently running kmeans on a dataset generated from radiation data.  From time to time the algorithm fails to converge (typically kmeans takes several seconds for the ~2 million points, have let it run overnight).

On the other hand I have a second issue with the same data set, it will sometimes fail with:

```thread 'main' panicked at 'WeightedChoice::new called with a total weight of 0', /home/omnipotententity/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.4.3/src/distributions/mod.rs:157:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:409
   6: <rand::distributions::WeightedChoice<'a, T>>::new
             at /home/omnipotententity/work/psd-dsp/<panic macros>:3
   7: rkm::initialize_plusplus
             at /home/omnipotententity/.cargo/registry/src/github.com-1ecc6299db9ec823/rkm-0.3.0/src/lib.rs:77
   8: rkm::kmeans_lloyd
             at /home/omnipotententity/.cargo/registry/src/github.com-1ecc6299db9ec823/rkm-0.3.0/src/lib.rs:143
   9: psd_dsp::main
             at src/main.rs:206
  10: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  15: main
  16: __libc_start_main
  17: _start
```

I'm currently using the version referenced on crates.io, 0.3.0.

**Comment by genbattle** [comment]
Hi, thanks for bringing this to my attention. Is it possible to provide a concise test case which can reproduce the issue, or even point me to a public dataset which will reproduce either of these issues?

You mentioned your dataset is ~2 million points, how many values are there for each point (dimensionality)? What `k` are you using? What type and size are the data values (u32, i64, f32, etc.)? The more information I have, the easier it will be to reproduce and fix this issue.

**Comment by genbattle** [comment]
In the meantime, you can work around the issue with initialization by replacing the `initialize_pluplus` function with one that just picks the first 4 points in the data set (standard kmeans). The kmeans++ initialization is supposed to give quicker conversions on average, but it was difficult to implement in Rust with the current `rand` library.

As for the issue with convergence, this is most likely down to the fact that I only check the immediately preceeding mean values for the termination condition, so if kmeans gets stuck in a bistable state ocsillating between two sets of means, it will never "converge". Just storing an additional set of historical means should fix this issue. This exact same issue would probably occur with [my original C++ implementation](https://github.com/genbattle/dkm/blob/master/include/dkm.hpp) as well.

**Comment by genbattle** [comment]
[OpenCV](https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_ml/py_kmeans/py_kmeans_opencv/py_kmeans_opencv.html) gets around the convergence issue by using either an epsilon measurement or iteration count for convergence, which may be a better way of solving the issue in this library.

**Comment by genbattle** [comment]
- [x] Use an enum parameter type to allow specification of multiple completion criteria
- [ ] Investigate initialization with large data sets (~2 million data points).

**Comment by OmnipotentEntity** [comment]
I will attempt to provide a minimal example from my data.  The convergence problem seems to be quite random, but the second problem is a bit more simple.  Here are two samples.  Each is the first 10 frequencies of a normalized abs(FFT) of a signal, the only difference is that the baseline of the second signal is adjusted by one part in 10 million (negative samples wrt baseline are clamped to zero, and this baseline adjustment brings it across an integer boundary, so the signals before FFT have a handful more zeroes, rather than very small non-zero values).  I'm attempting to find two groups.

[works.txt](https://github.com/genbattle/rkm/files/2456969/works.txt)
[fails.txt](https://github.com/genbattle/rkm/files/2456970/fails.txt)

**Comment by OmnipotentEntity** [comment]
Actually this is somewhat stupid and embarrassing.  fails.txt contains NaN entries.  It seems like for some reason the FFT results in NaN values for these cases.  Garbage in garbage out.

**Comment by genbattle** [comment]
This library now has the ability to set iteration and delta limits to prevent the algorithm from getting stuck in non-convergent states. Closing this issue as resolved.
